Removed report generations and added upload jobs to save the artefacts for later.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,10 +29,19 @@ jobs:
         run: |
             npm ci
             npm install -g karma-cli
-      
-      - name: Code linting
-        run: npm run lint --workspaces
 
+      - name: Code Linting
+        run: npm run lint --workspaces
+      
+      - name: Upload Lint Results
+        uses: actions/upload-artifact@v4  # upload test results  
+        if: ${{ !cancelled() }}           # run this step even if previous step failed
+        with:
+          name: lint-results
+          path: |
+            tokenserver/reports/lint-results.xml
+            platform/reports/lint-results.xml
+             
       - name: Build the education platform
         id: build-platform
         if: success() || failure()
@@ -42,6 +51,13 @@ jobs:
         id: run-unit-tests
         if: success() || failure() && steps.build-platform.outcome == 'success'
         run: npm test --workspaces
+
+      - name: Upload Test Results
+        uses: actions/upload-artifact@v4  # upload test results  
+        if: ${{ !cancelled() }}           # run this step even if previous step failed
+        with:
+          name: test-results-ubuntu
+          path: "platform/reports/*.xml"
         
   build-mac: 
     runs-on: macos-latest
@@ -73,33 +89,47 @@ jobs:
         if: success() || failure() && steps.build-platform.outcome == 'success'
         run: npm test --workspaces -- --browsers SafariNative
 
-  # build-win: 
-  #   runs-on: windows-latest
-  #   env:
-  #     EDGE_BIN: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
-  #   steps:
-  #     - uses: actions/checkout@v4
+      - name: Upload Test Results
+        uses: actions/upload-artifact@v4  # upload test results  
+        if: ${{ !cancelled() }}           # run this step even if previous step failed
+        with:
+          name: test-results-mac
+          path: "platform/reports/*.xml"
+
+  build-win: 
+     runs-on: windows-latest
+     env:
+      EDGE_BIN: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
+     steps:
+       - uses: actions/checkout@v4
                   
-  #     - name: Setup node 18
-  #       uses: actions/setup-node@v4
-  #       with: 
-  #         node-version: 18
+       - name: Setup node 18
+         uses: actions/setup-node@v4
+         with: 
+           node-version: 18
           
-  #     - name: Install node dependencies
-  #       run: |
-  #           npm ci
-  #           npm install -g karma-cli
+       - name: Install node dependencies
+         run: |
+             npm ci
+             npm install -g karma-cli
 
-  #     - name: Setup edge driver
-  #       run: |
-  #           choco install selenium-chromium-edge-driver
+       - name: Setup edge driver
+         run: |
+             choco install selenium-chromium-edge-driver
 
-  #     - name: Build the education platform
-  #       id: build-platform
-  #       if: success() || failure()
-  #       run: npm run build --workspaces
+       - name: Build the education platform
+         id: build-platform
+         if: success() || failure()
+         run: npm run build --workspaces
 
-  #     - name: Run the unit tests
-  #       id: run-unit-tests
-  #       if: success() || failure() && steps.build-platform.outcome == 'success'
-  #       run: npm test --workspaces -- --browsers EdgeHeadless
+       - name: Run the unit tests
+         id: run-unit-tests
+         if: success() || failure() && steps.build-platform.outcome == 'success'
+         run: npm test --workspaces -- --browsers EdgeHeadless
+
+       - name: Upload Test Results
+         uses: actions/upload-artifact@v4  # upload test results  
+         if: ${{ !cancelled() }}           # run this step even if previous step failed
+         with:
+          name: test-results-win
+          path: "platform/reports/*.xml"
